# Generated by Django 5.2.9 on 2026-01-02 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="List name (e.g., 'Week of Jan 6')", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(blank=True, help_text='Start date if generated from meal plan', null=True)),
                ('end_date', models.DateField(blank=True, help_text='End date if generated from meal plan', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_item', models.CharField(blank=True, help_text='Text for non-ingredient items', max_length=200)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('checked', models.BooleanField(default=False)),
                ('category_override', models.ForeignKey(blank=True, help_text='Override category for custom items', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_list_items', to='recipes.ingredientcategory')),
                ('ingredient', models.ForeignKey(blank=True, help_text='Ingredient from master list (blank for custom items)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_list_items', to='recipes.ingredient')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping.shoppinglist')),
            ],
            options={
                'ordering': ['ingredient__category__sort_order', 'ingredient__name', 'custom_item'],
            },
        ),
    ]
