# Generated by Django 5.2.9 on 2026-01-02 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], default='dinner', max_length=20)),
                ('custom_meal', models.CharField(blank=True, help_text="Text for non-recipe meals (e.g., 'Takeout', 'Leftovers')", max_length=200)),
                ('servings_override', models.PositiveIntegerField(blank=True, help_text="Override the recipe's default serving count", null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes for this specific meal')),
                ('recipe', models.ForeignKey(blank=True, help_text='Recipe for this meal (leave blank for custom meals)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_plans', to='recipes.recipe')),
            ],
            options={
                'ordering': ['date', 'meal_type'],
                'constraints': [models.UniqueConstraint(fields=('date', 'meal_type'), name='unique_meal_per_slot')],
            },
        ),
    ]
