# Generated by Django 5.2.9 on 2026-01-02 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mealplan',
            name='unique_meal_per_slot',
        ),
    ]
