# Generated by Django 5.2.9 on 2026-01-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_change_category_to_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cuisine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DishType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Dish type",
                "verbose_name_plural": "Dish types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Protein",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="categories",
        ),
        migrations.AddField(
            model_name="recipe",
            name="cuisines",
            field=models.ManyToManyField(
                blank=True, related_name="recipes", to="recipes.cuisine"
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="dish_types",
            field=models.ManyToManyField(
                blank=True, related_name="recipes", to="recipes.dishtype"
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="proteins",
            field=models.ManyToManyField(
                blank=True, related_name="recipes", to="recipes.protein"
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
